version: "2.1"

services:
  # BackstopJS
  backstop:
    hostname: backstop
    image: docksal/backstopjs
    volumes:
      - ${PROJECT_ROOT}/tests/backstop:/src
    # Keep the container running
    entrypoint: "top -b"

  # Behat
  behat:
    hostname: behat
    image: docksal/behat
    volumes:
      - ${PROJECT_ROOT}/tests/behat:/src
    # Keep the container running
    entrypoint: "top -b"

  # Selenium
  browser:
    hostname: browser
    # Pick/uncomment one
    image: selenium/standalone-chrome
    #image: selenium/standalone-firefox

  # Web (reports)
  web:
    hostname: web
    image: httpd:alpine
    volumes:
      - ${PROJECT_ROOT}/tests:/usr/local/apache2/htdocs/tests
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
