# Docker and Docker Compose based environment for Drupal.
# See https://github.com/docksal/docksal for more information and documentation.

version: "2"

services:
  # Web node
  web:
    hostname: web
    image: blinkreaction/drupal-apache:2.2-stable
    volumes:
      # Project root folder mapping
      - &project_root "../:/var/www"

  # CLI node
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: blinkreaction/drupal-cli:stable
    volumes:
      # Project root folder mapping
      - *project_root
      # Host home directory mapping (for SSH keys and ther credentials).
      # We try to map both options (b2d and Linux). The startup.sh script in cli container will decide which one to use.
      - /.home:/.home-b2d  # boot2docker-vagrant
      - ~/:/.home-linux   # Linux
      # Persistent data volume (home directory)
      - /home/docker

  # Selenium node
  browser:
    hostname: browser
    image: selenium/standalone-chrome
